# Generated by Django 6.0.2 on 2026-05-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аллергена')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг (для фильтрации)')),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название ингредиента')),
                ('calories_per_100g', models.PositiveIntegerField(default=0, verbose_name='Калорийность (ккал на 100г)')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание / процесс приготовления')),
                ('calories_per_person', models.PositiveIntegerField(verbose_name='Калорийность на 1 персону (ккал)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], max_length=20, verbose_name='Тип приема пищи')),
                ('suitable_for_diet', models.CharField(choices=[('classic', 'Классическая'), ('low_carb', 'Низкоуглеводная'), ('vegetarian', 'Вегетарианская'), ('keto', 'Кето')], default='classic', max_length=20, verbose_name='Подходит для диеты')),
                ('cooking_time', models.PositiveSmallIntegerField(default=30, verbose_name='Время приготовления (мин)')),
                ('contains_allergies', models.ManyToManyField(blank=True, to='core.allergy', verbose_name='Содержит аллергены')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.PositiveIntegerField(verbose_name='Количество (в граммах на 1 порцию)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецептах',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
