# Generated by Django 6.0.2 on 2026-05-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_allergy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories_per_person',
        ),
    ]
