# Generated by Django 6.0.2 on 2026-05-21 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('classic', 'Классическая'), ('low_carb', 'Низкоуглеводная'), ('vegetarian', 'Вегетарианская'), ('keto', 'Кето')], max_length=20, verbose_name='Тип питания')),
                ('period', models.IntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], verbose_name='Период (месяцев)')),
                ('persons_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество персон')),
                ('calories_per_day', models.PositiveIntegerField(default=2000, verbose_name='Калорий в день')),
                ('meals_count', models.PositiveSmallIntegerField(default=3, verbose_name='Количество приёмов пищи')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус')),
                ('allergies', models.ManyToManyField(blank=True, to='core.allergy', verbose_name='Аллергии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
