# Generated by Django 6.0.2 on 2026-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
    ]
