# Generated by Django 6.0.2 on 2026-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_review_subscription_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошел модерацию'),
        ),
    ]
