# Generated by Django 6.0.2 on 2026-05-22 07:15

import django.db.models.deletion
from django.db import migrations, models


MEAL_TYPES = [
    ("breakfast", "Завтрак"),
    ("lunch", "Обед"),
    ("dinner", "Ужин"),
    ("dessert", "Десерт"),
]


def seed_meal_types(apps, schema_editor):
    MealType = apps.get_model("core", "MealType")
    for code, name in MEAL_TYPES:
        MealType.objects.get_or_create(code=code, defaults={"name": name})


def link_recipes(apps, schema_editor):
    MealType = apps.get_model("core", "MealType")
    Recipe = apps.get_model("core", "Recipe")

    meal_type_map = {mt.code: mt for mt in MealType.objects.all()}

    for recipe in Recipe.objects.all():
        old_value = recipe._meal_type_old
        if old_value in meal_type_map:
            recipe.meal_type = meal_type_map[old_value]
            recipe.save(update_fields=["meal_type"])


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_promocode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип приёма пищи",
                "verbose_name_plural": "Типы приёмов пищи",
            },
        ),
        migrations.RunPython(seed_meal_types, reverse_seed),
        migrations.RemoveField(
            model_name="subscription",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="calories_per_day",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="meals_count",
        ),
        migrations.AddField(
            model_name="profile",
            name="allergies",
            field=models.ManyToManyField(
                blank=True, to="core.allergy", verbose_name="Аллергии"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="calories_per_day",
            field=models.PositiveIntegerField(
                default=2000, verbose_name="Калорий в день"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID платежа"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("paid", "Оплачена"),
                    ("cancelled", "Отменена"),
                    ("active", "Активна"),
                    ("expired", "Истекла"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="meals",
            field=models.ManyToManyField(
                blank=True, to="core.mealtype", verbose_name="Приёмы пищи"
            ),
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="meal_type",
            new_name="_meal_type_old",
        ),
        migrations.AddField(
            model_name="recipe",
            name="meal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="core.mealtype",
                verbose_name="Тип приема пищи",
                null=True,
            ),
        ),
        migrations.RunPython(link_recipes, reverse_seed),
        migrations.RemoveField(
            model_name="recipe",
            name="_meal_type_old",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="core.mealtype",
                verbose_name="Тип приема пищи",
            ),
        ),
    ]