# Generated by Django 6.0.2 on 2026-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_connect_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="calories_per_day",
        ),
        migrations.AddField(
            model_name="subscription",
            name="allergies",
            field=models.ManyToManyField(
                blank=True, to="core.allergy", verbose_name="Аллергии"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="calories_per_day",
            field=models.PositiveIntegerField(
                default=2000, verbose_name="Калорий в день"
            ),
        ),
    ]
