# Generated by Django 6.0.2 on 2026-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_move_order_fields_to_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="contains_allergies",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="contains_allergies",
            field=models.ManyToManyField(
                blank=True, to="core.allergy", verbose_name="Содержит аллергены"
            ),
        ),
    ]
