# Generated by Django 6.0.2 on 2026-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_subscription_period_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealtype",
            name="base_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Базовая цена"),
        ),
    ]
