# Generated by Django 6.0.2 on 2026-05-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_dailymenu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="calories_per_day",
        ),
    ]
