# Generated by Django 6.0.2 on 2026-05-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_calories_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.promocode",
                verbose_name="Промокод",
            ),
        ),
    ]
